routes/web.php
<?php

use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', [PostController::class,'index']);
Route::get('indexsoft', [PostController::class,'indexsoft'])->name('posts.indexsoft');
Route::get('restore/{id?}', [PostController::class,'restore'])->name('posts.restore');
Route::resource('posts',PostController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['title', 'body'];
//    all acsses
//    protected $guarded=[];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        // get deleted_at
//        $post=Post::withTrashed()
//            ->where('id', 1)->get();
        // restore deleted_at
//                $posts=Post::withTrashed()->where('id', 1)->restore();
//       return view('posts.index',compact('posts'));

        $posts= Post::all();
//        $posts= Post::get();
        return view('posts.index',compact('posts'));
//        $post= Post::where('id',1)->get();
//        return $post;
//        $post= Post::find(1);
//        return $post;
//        $post= Post::where('id',1)->first();
//        return $post;
//        $post= Post::findOrFail(1);
//        return $post;
//        $post= Post::firstWhere('id',1);
//        return $post;


    }

    public function create()
    {
        return view('posts.addpost');
    }

    public function store(StorePostRequest $request)
   {
//       Insret 1with save
//       $posts=new Post();
//       $posts->title = $request->title;
//       $posts->body = $request->body;
//        $posts->save();
//        return redirect()->route('posts.index')->with('add','Added Post');
//
//        return redirect()->back()->with('msg','Added Post');
//        Insret 2 with create
//      $request->validate([
//            'title' => 'required|unique:posts|max:255',
//            'body' => 'required',
//        ]);

            Post::create([
                'title' =>$request->title,
                'body' =>$request->body,
            ]);
        return redirect()->route('posts.index')->with('add','Added Post');
//      return redirect()->back()->with('msg','Added Post');

    }

    public function show(Post $post)
    {
        //
    }


    public function edit($id)
    {
        $post= Post::findOrFail($id);
        return view('posts.editpost',compact('post'));
    }


    public function update(UpdatePostRequest $request, $id)
    {
//        $posts= Post::findOrFail($id);
//        $posts->title = $request->title;
//        $posts->body = $request->body;
//        $posts->save();
//        return redirect()->back()->with('msg','Update Post');
        $posts= Post::findOrFail($id);
//        $posts->update($request->all());
        // important
        $posts->update([
            'title' => $request->title,
             'body' => $request->body,
        ]);
        return redirect()->route('posts.index')->with('msg','Update Post');

    }


    public function destroy($id)
    {
//        Post::findOrFail($id)->delete();
      Post::destroy($id);
//      $post =  Post::findOrFail($id);
//         $post->forceDelete($id);
      return redirect()->route('posts.index')->with('del','Delete Post');

    }
    public function indexsoft(){
        $posts= Post::onlyTrashed()->get();
         return view('posts.indexsoft',compact('posts'));
    }
    public function restore($id){
        $posts= Post::withTrashed()->where('id', $id)->restore();
//        return    $posts;
        return redirect()->route('posts.index')->with('res','Restored Post');
    }
}

resources/views/posts/addpost.blade.php
@extends('app')
@section('title')
    Add post
@endsection
@section('content')
    <h1 class=" mt-3" style="text-align: center">Add Post</h1>
    @include('posts.errors')
    <form action="{{route('posts.store')}}" method="POST">
        @csrf

        <div class="form-group mt-3">
            <label for="exampleInputEmail1">Title</label>
            <input id="title" type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="exampleFormControlTextarea1" rows="3" name="body">{{ old('body') }}</textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Add post</button>
    </form>
@endsection

resources/views/posts/editpost.blade.php
@extends('app')
@section('title')
    Add post
@endsection
@section('content')
    <h1 class=" mt-3" style="text-align: center">Edit Post</h1>
    @include('posts.errors')
    <form action="{{route('posts.update',$post->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group mt-3"  >
            <label for="exampleInputEmail1">Title</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="exampleInputEmail1" name="title" value=" {{$post->title}}">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="exampleFormControlTextarea1" name="body" rows="3">{{$post->body}}</textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-warning">Update</button>
    </form>
@endsection

resources/views/posts/errors.blade.php
@if(Session::has('add'))
        <div class="alert alert-success mt-2" role="alert">
            {{Session::get("add")}}
        </div>
    @endif
    @if(Session::has('res'))
        <div class="alert alert-info mt-2" role="alert">
            {{Session::get("res")}}
        </div>
    @endif
    @if(Session::has('msg'))
        <div class="alert alert-warning mt-2" role="alert">
            {{Session::get("msg")}}
        </div>
    @endif
    @if(Session::has('del'))
        <div class="alert alert-danger mt-2" role="alert">
            {{Session::get("del")}}
        </div>
    @endif


@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/posts/index.blade.php
@extends('app')
@section('title')
    Posts
@endsection
@section('content')
    @include('posts.errors')
    <table class="table" style="text-align: center">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Body</th>
            <th scope="col">Btn</th>
        </tr>
        </thead>
        <tbody>
        {{--        @foreach($posts as $post)--}}
        @forelse($posts as $post)
            <tr>
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$post->title}}</td>
                <td>{{$post->body}}</td>
                <td>
                    <a href="{{route('posts.create')}}" class="btn btn-primary btn-s">Add</a>
                    <a href="{{route('posts.edit',$post->id)}}" class="btn btn-warning btn-s">Edit</a>
                    <a href="{{route('posts.indexsoft')}}" class="btn btn-info btn-s">Restore</a>

                    <form action="{{route('posts.destroy',$post->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <input type="submit" value="Delete" class="btn btn-danger btn-s">
                    </form>
                    <!-- Button trigger modal -->
                {{--                <button type="button" class="btn btn-danger btn-s" data-toggle="modal" data-target="#exampleModal">--}}
                {{--                    Delete--}}
                {{--                </button>--}}

                <!-- Modal -->
                    {{--                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">--}}
                    {{--                    <div class="modal-dialog" role="document">--}}
                    {{--                        <div class="modal-content">--}}
                    {{--                            <div class="modal-header">--}}
                    {{--                                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>--}}
                    {{--                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                    {{--                                    <span aria-hidden="true">&times;</span>--}}
                    {{--                                </button>--}}
                    {{--                            </div>--}}
                    {{--                            <div class="modal-body">--}}
                    {{--                                Are you sure to delete?--}}
                    {{--                            </div>--}}
                    {{--                            <div class="modal-footer">--}}
                    {{--                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
                    {{--                               <a href="{{route('posts.destroy',$post->id)}}" class="btn btn-danger btn-s">Delete</a>--}}
                    {{--                            </div>--}}
                    {{--                        </div>--}}
                    {{--                    </div>--}}
                    {{--                </div>--}}
                </td>
                @empty
                    <td colspan="3" style="text-align: center">NO Post</td>
                    <td>
                        <a href="{{route('posts.create')}}" class="btn btn-primary btn-s">Add</a>
                        <a href="{{route('posts.indexsoft')}}" class="btn btn-info btn-s">Soft Deleted</a>
                    </td>
        @endforelse
        {{--        @endforeach--}}
        </tbody>
    </table>
@endsection

resources/views/posts/indexsoft.blade.php
@extends('app')
@section('title')
   Soft Posts
@endsection
@section('content')

    <table class="table" style="text-align: center">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Body</th>
            <th scope="col">Btn</th>
        </tr>
        </thead>
        <tbody>
{{--        @foreach($posts as $post)--}}
            @forelse($posts as $post)
            <tr>
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$post->title}}</td>
                <td>{{$post->body}}</td>
                <td>
                    <a href="{{route('posts.restore',$post->id)}}" class="btn btn-secondary btn-s">Restore</a>
{{--                    <a href="{{route('posts.edit',$post->id)}}" class="btn btn-warning btn-s">Edit</a>--}}

{{--                    <form action="{{route('posts.destroy',$post->id)}}" method="POST">--}}
{{--                        @csrf--}}
{{--                        @method('DELETE')--}}
{{--                        <input type="submit" value="Delete" class="btn btn-danger btn-s">--}}
{{--                    </form>--}}


                    <!-- Button trigger modal -->
                {{--                <button type="button" class="btn btn-danger btn-s" data-toggle="modal" data-target="#exampleModal">--}}
                {{--                    Delete--}}
                {{--                </button>--}}

                <!-- Modal -->
                    {{--                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">--}}
                    {{--                    <div class="modal-dialog" role="document">--}}
                    {{--                        <div class="modal-content">--}}
                    {{--                            <div class="modal-header">--}}
                    {{--                                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>--}}
                    {{--                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                    {{--                                    <span aria-hidden="true">&times;</span>--}}
                    {{--                                </button>--}}
                    {{--                            </div>--}}
                    {{--                            <div class="modal-body">--}}
                    {{--                                Are you sure to delete?--}}
                    {{--                            </div>--}}
                    {{--                            <div class="modal-footer">--}}
                    {{--                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
                    {{--                               <a href="{{route('posts.destroy',$post->id)}}" class="btn btn-danger btn-s">Delete</a>--}}
                    {{--                            </div>--}}
                    {{--                        </div>--}}
                    {{--                    </div>--}}
                    {{--                </div>--}}


                </td>
            @empty
                    <td colspan="4" style="text-align: center" class="alert alert-info mt-2">NO Post Deleted</td>

            @endforelse
{{--        @endforeach--}}
        </tbody>
    </table>
@endsection